-- ===================================================================
-- Migration: Add Funding/Trading Account Structure to cash_flows
-- ===================================================================
-- 
-- STRATEGY: "Auto-Sweep" Backfill
-- 
-- In the old model, every Deposit/Transfer went directly into the 
-- trading balance. To preserve historical Trading Account balances 
-- perfectly, we:
--
-- 1. Mark ALL existing rows as account_type = 'Funding'
--    (except Saham stock-trade rows which go directly to 'Trading')
-- 2. For each existing inflow (Deposit/Transfer Masuk), create a 
--    paired sweep: Funding Transfer Keluar + Trading Transfer Masuk
-- 3. For each existing outflow (Withdraw/Transfer Keluar), create a
--    paired sweep: Trading Transfer Keluar + Funding Transfer Masuk
--
-- Result: Funding balances net to zero (every deposit was swept out),
-- and Trading balances match exactly what the old system computed.
-- ===================================================================

-- Step 1: Add the account_type column
ALTER TABLE cash_flows 
  ADD COLUMN IF NOT EXISTS account_type text 
  CHECK (account_type IN ('Funding', 'Trading'));

-- Step 2: Backfill Saham stock-trade rows as 'Trading'
-- These are auto-generated by StockTransactionEntry and represent 
-- actual trading activity, not external money movement.
UPDATE cash_flows 
SET account_type = 'Trading' 
WHERE desk = 'Saham' 
  AND (catatan LIKE 'Buy %' OR catatan LIKE 'Sell %')
  AND account_type IS NULL;

-- Step 3: Backfill all remaining existing rows as 'Funding'
UPDATE cash_flows 
SET account_type = 'Funding' 
WHERE account_type IS NULL;

-- Step 4: Auto-sweep — for every Funding inflow, create paired 
-- Funding→Trading transfer so Trading balance matches old totals.
--
-- For Deposits and Transfer Masuk: money came in via Funding, 
-- we create a sweep pair that moves it to Trading.
INSERT INTO cash_flows (tanggal, tipe, jumlah, desk, desk_tujuan, currency, catatan, account_type)
SELECT 
  tanggal, 
  'Transfer Keluar', 
  jumlah, 
  desk, 
  NULL, 
  currency, 
  '[Auto-Sweep] ' || tipe || ' → Trading', 
  'Funding'
FROM cash_flows 
WHERE account_type = 'Funding' 
  AND tipe IN ('Deposit', 'Transfer Masuk');

INSERT INTO cash_flows (tanggal, tipe, jumlah, desk, desk_tujuan, currency, catatan, account_type)
SELECT 
  tanggal, 
  'Transfer Masuk', 
  jumlah, 
  desk, 
  NULL, 
  currency, 
  '[Auto-Sweep] ' || tipe || ' → Trading', 
  'Trading'
FROM cash_flows 
WHERE account_type = 'Funding' 
  AND tipe IN ('Deposit', 'Transfer Masuk')
  AND catatan NOT LIKE '[Auto-Sweep]%';

-- Step 5: Auto-sweep — for every Funding outflow, create paired 
-- Trading→Funding transfer so Trading balance is correctly debited.
--
-- For Withdraws and Transfer Keluar: money left via Funding,
-- we create a sweep pair that pulls it from Trading first.
INSERT INTO cash_flows (tanggal, tipe, jumlah, desk, desk_tujuan, currency, catatan, account_type)
SELECT 
  tanggal, 
  'Transfer Keluar', 
  jumlah, 
  desk, 
  NULL, 
  currency, 
  '[Auto-Sweep] ' || tipe || ' ← Trading', 
  'Trading'
FROM cash_flows 
WHERE account_type = 'Funding' 
  AND tipe IN ('Withdraw', 'Transfer Keluar');

INSERT INTO cash_flows (tanggal, tipe, jumlah, desk, desk_tujuan, currency, catatan, account_type)
SELECT 
  tanggal, 
  'Transfer Masuk', 
  jumlah, 
  desk, 
  NULL, 
  currency, 
  '[Auto-Sweep] ' || tipe || ' ← Trading', 
  'Funding'
FROM cash_flows 
WHERE account_type = 'Funding' 
  AND tipe IN ('Withdraw', 'Transfer Keluar')
  AND catatan NOT LIKE '[Auto-Sweep]%';

-- Step 6: Make account_type NOT NULL going forward
ALTER TABLE cash_flows 
  ALTER COLUMN account_type SET NOT NULL;

-- Step 7: Add default for convenience (new rows must always specify it,
-- but a default prevents accidental NULLs from old code paths)
ALTER TABLE cash_flows 
  ALTER COLUMN account_type SET DEFAULT 'Funding';
